def menu_principal():
    print("")
    print("=="* 20)
    print("          SYSTEMA(Claro)")
    print("=="* 20)
    print("")
    print("="*10 +" Modulo de Gestio "+ "="*10)
    print("     1. Para agregar usuario")
    print("     2. Para bucascar usuario")
    print("     3. Para eliminar usuario")
    print("     4. Para modificar usuario")
    print("     5. Para agregar producto")
    print("     6. Para buscar  producto")
    print("     7. Para eliminar producto")
    print("     8. Para modifiar producto")
    print("     9. Para agregar servicio")
    print("    10. Para buscar servicio")
    print("    11. Para eliminar servicio")
    print("    12. Para modificar servicio")
    print("=="* 20)
    print("")
    print("="*10 +" Modulo de Reportes "+ "="*10)
    print("    13. Para agregar reclamo")
    print("    14. Para buscar reclamo")
    print("    15. Para eliminar reclamo")
    print("    16. Para modificar reclamo")
    print("    17. Para agregar sugerencia")
    print("    18. Para buscar sugerencia")
    print("    19. Para eliminar sugerencia")
    print("    20. Para modificar sugerencia")
    print("=="* 20)
    print("")
    print("="*10 +"  Modulo de Ventas "+ "="*10)
    print("    21. Para agregar venta de producto" "\n" "        o servicio")
    print("    22. Para buscar venta de producto" "\n" "        o servicio")
    print("    23. Para eliminar venta de producto" "\n" "        o servicio")
    print("    24. Para modificar venta de producto" "\n" "        o servicio")
    print("=="* 20)
    print("    25. para salir")
    print("")
    

def pedir_opcion():
    try:
        print("//"*20)
        op = int(input("  Ingrese su opcion: "))
        print("//"*20)
        
        return op
        
    except Exception:
        print("--"*20)
        print("valor invalido")