def menu_principal():
    print("")
    print("=="* 20)
    print("          Estructura(Tofu)")
    print("=="* 20)
    print("")
    print("="*10 +" Modulo de Gestion "+ "="*10)
    print("     1. Para agregar usuario")
    print("     2. Para bucascar usuario")
    print("     3. Para eliminar usuario")
    print("     4. Para modificar usuario")
    print("=="* 20)
    print("")
    print("="*10 +" Modulo de Servicios "+ "="*10)
    print("     5. Para agregar producto")
    print("     6. Para buscar  producto")
    print("     7. Para eliminar producto")
    print("     8. Para modifiar producto")
    print("     9. Para agregar servicio")
    print("    10. Para buscar servicio")
    print("    11. Para eliminar servicio")
    print("    12. Para modificar servicio")
    print("    13. Para agregar promocion")
    print("    14. Para buscar promocion")
    print("    15. Para eliminar promocion")
    print("    16. Para modificar promocion")
    print("=="* 20)
    print("")
    print("="*10 +" Modulo de Reportes "+ "="*10)
    print("    17. Para agregar reclamo")
    print("    18. Para buscar reclamo")
    print("    19. Para eliminar reclamo")
    print("    20. Para modificar reclamo")
    print("    21. Para agregar sugerencia")
    print("    22. Para buscar sugerencia")
    print("    23. Para eliminar sugerencia")
    print("    24. Para modificar sugerencia")
    print("=="* 20)
    print("")
    print("="*10 +"  Modulo de Ventas "+ "="*10)
    print("    25. Para agregar venta de producto" "\n" "        o servicio")
    print("    26. Para buscar venta de producto" "\n" "        o servicio")
    print("    27. Para eliminar venta de producto" "\n" "        o servicio")
    print("    28. Para modificar venta de producto" "\n" "        o servicio")
    print("=="* 20)
    print("    29. para salir")
    print("")
    

def pedir_opcion():
    try:
        print("//"*20)
        op = int(input("  Ingrese su opcion: "))
        print("//"*20)
        
        return op
        
    except Exception:
        print("--"*20)
        print("valor invalido")